/* Simulation code for ROS_Sampler generated by the OpenModelica Compiler OpenModelica 1.17.0~5-gb8b118d. */
#if !defined(ROS_Sampler__MODEL_H)
#define ROS_Sampler__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "ROS_Sampler_functions.h"

#define ROS__Socket__Call_index 0

extern void ROS_Sampler_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void ROS_Sampler_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int ROS_Sampler_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int ROS_Sampler_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int ROS_Sampler_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int ROS_Sampler_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int ROS_Sampler_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int ROS_Sampler_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int ROS_Sampler_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int ROS_Sampler_checkForAsserts(DATA *data, threadData_t *threadData);
extern int ROS_Sampler_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int ROS_Sampler_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int ROS_Sampler_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* ROS_Sampler_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* ROS_Sampler_relationDescription(int i);
extern void ROS_Sampler_function_initSample(DATA *data, threadData_t *threadData);
extern int ROS_Sampler_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ROS_Sampler_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ROS_Sampler_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ROS_Sampler_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ROS_Sampler_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ROS_Sampler_initialAnalyticJacobianF(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ROS_Sampler_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ROS_Sampler_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ROS_Sampler_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ROS_Sampler_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ROS_Sampler_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ROS_Sampler_functionJacF_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* ROS_Sampler_linear_model_frame(void);
extern const char* ROS_Sampler_linear_model_datarecovery_frame(void);
extern int ROS_Sampler_mayer(DATA* data, modelica_real** res, short *);
extern int ROS_Sampler_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int ROS_Sampler_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int ROS_Sampler_setInputData(DATA *data, const modelica_boolean file);
extern int ROS_Sampler_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void ROS_Sampler_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void ROS_Sampler_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int ROS_Sampler_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void ROS_Sampler_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void ROS_Sampler_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int ROS_Sampler_inputNames(DATA* data, char ** names);
extern int ROS_Sampler_dataReconciliationInputNames(DATA* data, char ** names);
extern int ROS_Sampler_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int ROS_Sampler_functionLocalKnownVars(DATA*, threadData_t*);
extern int ROS_Sampler_symbolicInlineSystem(DATA*, threadData_t*);

#include "ROS_Sampler_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(ROS_Sampler__MODEL_H) */


