/* Additional record code for ROS_Sampler generated by the OpenModelica Compiler OpenModelica 1.17.0~5-gb8b118d. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "ROS_Sampler_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

