# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -fPIC -mfpmath=sse -fno-dollars-in-identifiers ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"/usr/bin/../include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=Glider_Lib_Modelica_ROS_GenericGlider_mass_explicit -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=6 -DOMC_NUM_NONLINEAR_SYSTEMS=3 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -llapack -lblas -lm -lm -lomcgc -lpthread -rdynamic -Wl,--no-undefined
LDFLAGS=-L"/usr/bin/../lib/x86_64-linux-gnu/omc" -L"/usr/bin/../lib" -Wl,-rpath,"/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath,"/usr/bin/../lib"   $(RUNTIME_LIBS) 
DIREXTRA=-L"/home/automata/repos/Glider_Lib_Modelica_ROS"
MAINFILE=Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit.c
MAINOBJ=Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit.o
CFILES=Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_functions.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_records.c \
Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_01exo.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_02nls.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_03lsy.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_04set.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_05evt.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_06inz.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_07dly.c \
Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_08bnd.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_09alg.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_10asr.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_11mix.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_12jac.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_13opt.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_14lnz.c \
Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_15syn.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_16dae.c Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_17inl.c \
   Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_08bnd_part0.c\
   Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_08bnd_part1.c\
   Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_06inz_part0.c\
   Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_06inz_part1.c

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit.makefile Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_literals.h Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_functions.h Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_literals.h $(OFILES)
	$(CC) -I. -o Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_records.o $(MAINOBJ)

bundle:
	@tar -cvf Glider_Lib_Modelica_ROS.GenericGlider_mass_explicit_Files.tar $(GENERATEDFILES)