/* Additional record code for TestGlider generated by the OpenModelica Compiler OpenModelica 1.17.0~5-gb8b118d. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "TestGlider_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Modelica_Mechanics_MultiBody_Frames_Orientation__desc_added 1
const char* Modelica_Mechanics_MultiBody_Frames_Orientation__desc__fields[2] = {"T","w"};
struct record_description Modelica_Mechanics_MultiBody_Frames_Orientation__desc = {
  "Modelica_Mechanics_MultiBody_Frames_Orientation", /* package_record__X */
  "Modelica.Mechanics.MultiBody.Frames.Orientation", /* package.record_X */
  Modelica_Mechanics_MultiBody_Frames_Orientation__desc__fields
};

void Modelica_Mechanics_MultiBody_Frames_Orientation_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Mechanics_MultiBody_Frames_Orientation* ths = (Modelica_Mechanics_MultiBody_Frames_Orientation*)(v_ths);
  alloc_real_array(&(ths->_T), 2, (_index_t)3, (_index_t)3); // ths->_T has no default value.
  alloc_real_array(&(ths->_w), 1, (_index_t)3); // ths->_w has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Modelica_Mechanics_MultiBody_Frames_Orientation omc_Modelica_Mechanics_MultiBody_Frames_Orientation(threadData_t *threadData , real_array  in_T, real_array  in_w) {
  Modelica_Mechanics_MultiBody_Frames_Orientation dst;
  // TODO Improve me. No need to initalize the record memebers with defaults in Modelica_Mechanics_MultiBody_Frames_Orientation_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Modelica_Mechanics_MultiBody_Frames_Orientation_construct(threadData, dst);
  real_array_copy_data( in_T, dst._T);
  real_array_copy_data( in_w, dst._w);
  return dst;
}
*/

void Modelica_Mechanics_MultiBody_Frames_Orientation_copy_p(void* v_src, void* v_dst) {
  Modelica_Mechanics_MultiBody_Frames_Orientation* src = (Modelica_Mechanics_MultiBody_Frames_Orientation*)(v_src);
  Modelica_Mechanics_MultiBody_Frames_Orientation* dst = (Modelica_Mechanics_MultiBody_Frames_Orientation*)(v_dst);
  real_array_copy_data(src->_T, dst->_T);
  real_array_copy_data(src->_w, dst->_w);
}

#ifdef __cplusplus
}
#endif

